apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-metricsfetcher-job
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 5
  activeDeadlineSeconds: 240
  template:
    metadata:
      name: kafka-metricsfetcher-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: kafka-rebalance
        image: {{ .Values.global.kafka_rebalance_image | quote }}
        imagePullPolicy: IfNotPresent
        command: ["kafkakit-prometheus-metricsfetcher","--zk-addr", {{.Values.zk_url | quote}}, "--prometheus-url",{{ .Values.prometheus_url | quote }},"--broker-storage-query",{{ .Values.broker_storage_query | quote}}, "--partition-size-query", {{.Values.partition_size_query | quote}}]